# -- General Info --------------------------------------------------------------
host    : localhost
port    : 8888
timezone: Europe/Amsterdam
timeout : 6000

# -- Services ------------------------------------------------------------------
mongo:
  - name    : primary
    host    : ds047484.mongolab.com
    port    : 47484
    db      : moneyback
    user	: root
    password: moneyback

#appnima:
#	key		: NTRmNzhjM2ZiNmFmNzI5MjM0YzI3ZTA2OkpIeHlUUFh3dmZBYU5rMWZaaVcwVkwwMnZRMXNiNHo=
#	host	: api.appnima.com
#	protocol: http
#	port	: 80