# -- General Info --------------------------------------------------------------
host    : localhost
port    : 8888
timezone: Europe/Amsterdam
timeout : 6000

# -- Services ------------------------------------------------------------------
mongo:
  - name    : primary
    host    : ds027698.mongolab.com
    port    : 27698
    db      : persona
    user	: money
    password: back

#appnima:
#	key		: NTRmNzhjM2ZiNmFmNzI5MjM0YzI3ZTA2OkpIeHlUUFh3dmZBYU5rMWZaaVcwVkwwMnZRMXNiNHo=
#	host	: api.appnima.com
#	protocol: http
#	port	: 80