// Generated by CoffeeScript 1.7.1
"use strict";
Atoms.$(function() {
  console.log("------------------------------------------------------------");
  console.log("Atoms v" + Atoms.version + " (Atoms.App v" + Atoms.App.version + ")");
  console.log("------------------------------------------------------------");
  Atoms.Url.path("inicio/personas");
  return __.Article.Inicio.fetch();
});
